/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Chang Access Level For CPU PAL & NPAL
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdio.h>
void SwitchAccessLevel(void)
{
	/*Read Control Registers*/
		__asm volatile ("MRS R0,CONTROL");

		/*Modify , oring with one*/
		__asm volatile ("ORR R0,#0X01");

		/*write a new value into control Resg*/
		__asm volatile ("MSR CONTROL,R0");

		/*NOW NPAL*/
}
void GenerateInterrupt(void)
{
	uint32_t* pSTIR= (uint32_t*)0xE000EF00;
	uint32_t* pISER0= (uint32_t*)0xE000E100;

	//Enable IRQ3 Interrupt
	*pISER0 |= 1<<3;

	//Generate Software interrupt for IRQ3
	*pSTIR = (3 &0x1FF);
}


int main(void)
{
	printf("In Thread mode, before interrupt\n");

	SwitchAccessLevel();

	GenerateInterrupt();

	printf("In Thread mode, after interrupt\n");

    /* Loop forever */
	for(;;);
}

void RTC_WKUP_IRQHandler (void)
{
	printf("In handler mode :  ISR\n");
}

void HardFault_Handler(void)
{
	printf("Inside Hardfaut\n");
}



